### ISSUE TITLE
Sorting/filtering for todo list

### ISSUE THREAD

**Issue by shuhaowu** [shuhaowu/projecto#2]
More advanced sorting and filter is needed than the current iteration. Things to do:
- [ ] A sorting framework based on authors, due date, creation date, or others.
- [ ] A client side sorting UI that's easy to use
- [ ](Investigate) is client side sorting sufficient?
  - Probably not, as we need pagination for client side sorting
- [x] Filtering of todo list based on tags.
  - No pagination yet. 
  - Needs caching.

**Comment by shuhaowu** [comment]
Is this done?

**Comment by shuhaowu** [comment]
No. unittesting filtering is still not available.
